[metadata]
name = packages-python
version = 0.1.0
description = Packages Delivery - Core Python package
author = Major Hamblin
license = GPL-3.0
long_description = file: README.md
long_description_content_type = text/markdown

[options]
python_requires = >=3.10
packages = find:
package_dir =
    = src

[options.packages.find]
where = src
include = packages_python*

[options.package_data]
packages_python = *
